# Gibrán leonardo Chávez González

## Act. Árboles de decisión

In [221]:
import pandas as pd
import numpy as np

Creación del dataframe a trabajar

In [222]:
data = pd.DataFrame()

Introducimos valores

In [223]:
data['Género'] = ['H', 'M', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'M', 'M', 'H', 'H', 'H', 'H', 'H']
data['Edad'] = [21, 19, 21, 19, 20, 21, 22, 21, 19, 21, 19, 21, 20, 20, 19, 19]
data['Estatura'] = [1.73, 1.62, 1.73, 1.69, 1.75, 1.8, 1.7, 1.75, 1.66, 1.64, 1.62, 1.85, 1.75, 1.66, 1.7, 1.64]

data

   Género  Edad  Estatura
0       H    21      1.73
1       M    19      1.62
2       H    21      1.73
3       H    19      1.69
4       H    20      1.75
5       H    21      1.80
6       H    22      1.70
7       H    21      1.75
8       H    19      1.66
9       M    21      1.64
10      M    19      1.62
11      H    21      1.85
12      H    20      1.75
13      H    20      1.66
14      H    19      1.70
15      H    19      1.64

Filtramos a los hombres con 21 o más años de edad

In [224]:
data_filtrada = data[(data['Edad'] >= 21) & (data['Género'] == 'H')]
data_filtrada

   Género  Edad  Estatura
0       H    21      1.73
2       H    21      1.73
5       H    21      1.80
6       H    22      1.70
7       H    21      1.75
11      H    21      1.85

In [225]:
data_filtrada['Estatura'].mean()

np.float64(1.76)

Filtramos a los hombres con menos de 21 años de edad

In [226]:
data_filtrada2 = data[(data['Edad'] < 21) & (data['Género'] == 'H')]
data_filtrada2

   Género  Edad  Estatura
3       H    19      1.69
4       H    20      1.75
8       H    19      1.66
12      H    20      1.75
13      H    20      1.66
14      H    19      1.70
15      H    19      1.64

In [227]:
data_filtrada2['Estatura'].mean()

np.float64(1.6928571428571428)

Filtramos a las mujeres con 21 o más años de edad

In [228]:
data_filtrada3 = data[(data['Edad'] >= 21) & (data['Género'] == 'M')]
data_filtrada3

  Género  Edad  Estatura
9      M    21      1.64

In [229]:
data_filtrada3['Estatura'].mean()

np.float64(1.64)

Filtramos a las mujeres con menos de 21 años de edad

In [230]:
data_filtrada4 = data[(data['Edad'] < 21) & (data['Género'] == 'M')]
data_filtrada4

   Género  Edad  Estatura
1       M    19      1.62
10      M    19      1.62

In [231]:
data_filtrada4['Estatura'].mean()

np.float64(1.62)

### **Ejercicio**

1. Tomar $advertising.csv$ y hacer una regresion lineal simple

2. Calcular $R^2$ de (1)

3. Usar un árbol de decisión para regresión sobre el mismo dataset

4. Calcular $R^2$ de (3)

5. Repetir (1-4) con trani-test split 50/50

**Escalamiento no necesario**

In [232]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

Carga del dataset

In [233]:
df = pd.read_csv('Advertising.csv')
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

Decisión de variables

In [234]:
X = df.drop(['Unnamed: 0', 'sales'], axis=1)
y = df['sales']

Regresión lineal simple

In [235]:
lr = LinearRegression()

In [236]:
pipeline = Pipeline(
    steps=[('model', lr)]
)

In [237]:
pipeline.fit(X, y)

Pipeline(steps=[('model', LinearRegression())])

$R^2$

In [238]:
pipeline.named_steps['model'].score(X, y)

0.8972106381789522

Árbol de decisión

In [239]:
tree_model = DecisionTreeRegressor(random_state=42)

In [240]:
pipeline_for_tr = Pipeline(
    steps=[
        ('model', tree_model)
    ]
)

In [241]:
pipeline_for_tr.fit(X, y)

Pipeline(steps=[('model', DecisionTreeRegressor(random_state=42))])

$R^2$

In [242]:
pipeline_for_tr.named_steps['model'].score(X, y)

1.0

Separamiento con train-test 50/50

In [243]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

Entrenamiento con train (regresión lineal)

In [244]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('model', LinearRegression())])

$R^2$ train

In [245]:
pipeline.named_steps['model'].score(X_train, y_train)

0.9042613648908892

$R^2$ test

In [246]:
pipeline.named_steps['model'].score(X_test, y_test)

0.8721004816045136

Entrenamiento con train (árbol de decisión)

In [247]:
pipeline_for_tr.fit(X_train, y_train)

Pipeline(steps=[('model', DecisionTreeRegressor(random_state=42))])

$R^2$ train

In [248]:
pipeline_for_tr.named_steps['model'].score(X_train, y_train)

1.0

$R^2$ test

In [249]:
pipeline_for_tr.named_steps['model'].score(X_test, y_test)

0.9344975035059896